# Generated by Django 5.2.8 on 2026-02-23 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_businessproposal_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='interested_investors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'investor'}, related_name='interested_proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
