# Generated by Django 5.2.8 on 2026-02-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_business_sector_user_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('moderator', 'Moderator'), ('investor', 'Investor'), ('admin', 'Admin')], max_length=20),
        ),
    ]
